apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: zcp-system
data:
  kibana.yml: |-
    server.name: kibana
    server.host: "0"
    server.port: "5602"
    elasticsearch.url: "http://elasticsearch:9200"
    xpack.monitoring.enabled: true 
    xpack.security.enabled: false
    xpack.graph.enabled: false
    xpack.reporting.enabled: false
    xpack.ml.enabled: false
